# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-11-23 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='no_resi',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
